foldersTree = gFld("Folder Tree","D:\projects\delphi\FTC\Deployment\home.html")
      aux1 = insFld(foldersTree, gFld("New Folder",""))
         insDoc(aux1,gLnk(0,"New Folder",""))
initializeDocument()
clickOnNode(1)
