foldersTree = gFld("Folder Tree","C:\Program Files\Borland\Delphi5\Projects\Ftc2\home.html")
      aux1 = insFld(foldersTree, gFld("Search Engines",""))
         insDoc(aux1,gLnk(2,"YAHOO","www.yahoo.com"))
         insDoc(aux1,gLnk(2,"GOOGLE","www.google.com"))
         insDoc(aux1,gLnk(2,"LYCOS","www.lycos.com"))
         insDoc(aux1,gLnk(2,"GO","www.go.com"))
         insDoc(aux1,gLnk(2,"WEBCRAWLER","www.webcrawler.com"))
initializeDocument()
clickOnNode(1)
